export const MOVIE_TYPE = 'movie' as const
export const MOVIE_KEYWORDS = [
  'action',
  'adventure',
  'animation',
  'biography',
  'christmas',
  'classic',
  'comedy',
  'crime',
  'documentary',
  'drama',
  'family',
  'fantasy',
  'friendship',
  'history',
  'horror',
  'infant',
  'intrigue',
  'love',
  'mystery',
  'musical',
  'police',
  'romance',
  'sports',
  'suspense',
  'teen',
  'thriller',
  'war',
  'western',
  'science fiction',
  'travel',
] as const
